# Generated by Django 4.1.5 on 2023-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='toxicity',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
